#!/usr/bin/env python3
"""Reproducible EDA report generator for the Online Shoppers dataset.

Computes target balance, numeric distributions, categorical frequencies, and
per-category conversion rates from the raw dataset, then writes a Markdown
report to docs/eda-report.md. Every number in the report is computed by this
script at run time; nothing is hand-transcribed.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from conversion_router.data.load import load_raw_dataset
from conversion_router.data.validate import validate_raw_schema

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REPORT_PATH = PROJECT_ROOT / "docs" / "eda-report.md"

NUMERIC_COLUMNS = (
    "Administrative",
    "Administrative_Duration",
    "Informational",
    "Informational_Duration",
    "ProductRelated",
    "ProductRelated_Duration",
    "BounceRates",
    "ExitRates",
    "PageValues",
    "SpecialDay",
)

CATEGORICAL_COLUMNS = (
    "Month",
    "VisitorType",
    "Weekend",
    "OperatingSystems",
    "Browser",
    "Region",
    "TrafficType",
)


def conversion_rate_by(df: pd.DataFrame, column: str) -> pd.DataFrame:
    grouped = df.groupby(column, observed=True)["Revenue"].agg(["mean", "count"])
    grouped = grouped.rename(columns={"mean": "conversion_rate", "count": "n_sessions"})
    return grouped.sort_values("conversion_rate", ascending=False)


def markdown_table(df: pd.DataFrame, float_cols: tuple[str, ...] = ()) -> str:
    formatted = df.copy()
    for col in float_cols:
        formatted[col] = formatted[col].map(lambda v: f"{v:.4f}")
    header = "| " + " | ".join([formatted.index.name or "value"] + list(formatted.columns)) + " |"
    sep = "|" + "|".join(["---"] * (len(formatted.columns) + 1)) + "|"
    rows = [
        "| " + " | ".join([str(idx)] + [str(v) for v in row]) + " |"
        for idx, row in zip(formatted.index, formatted.values, strict=True)
    ]
    return "\n".join([header, sep] + rows)


def main() -> None:
    df = load_raw_dataset()
    validate_raw_schema(df)

    n_total = len(df)
    n_positive = int(df["Revenue"].sum())
    n_negative = n_total - n_positive
    positive_rate = n_positive / n_total

    numeric_summary = df[list(NUMERIC_COLUMNS)].describe().T[
        ["mean", "std", "min", "50%", "max"]
    ]
    numeric_summary.index.name = "feature"

    visitor_rates = conversion_rate_by(df, "VisitorType")
    weekend_rates = conversion_rate_by(df, "Weekend")
    month_rates = conversion_rate_by(df, "Month")
    traffic_rates = conversion_rate_by(df, "TrafficType")

    overall_bounce_mean = df["BounceRates"].mean()
    converted_bounce_mean = df.loc[df["Revenue"], "BounceRates"].mean()
    not_converted_bounce_mean = df.loc[~df["Revenue"], "BounceRates"].mean()

    converted_pv_mean = df.loc[df["Revenue"], "ProductRelated_Duration"].mean()
    not_converted_pv_mean = df.loc[~df["Revenue"], "ProductRelated_Duration"].mean()

    best_month = month_rates["conversion_rate"].idxmax()
    worst_month = month_rates["conversion_rate"].idxmin()

    returning_rate = visitor_rates.loc["Returning_Visitor", "conversion_rate"]
    new_rate = visitor_rates.loc["New_Visitor", "conversion_rate"]

    weekend_rate = weekend_rates.loc[True, "conversion_rate"]
    weekday_rate = weekend_rates.loc[False, "conversion_rate"]

    lines = []
    lines.append("# EDA and Class-Imbalance Report")
    lines.append("")
    lines.append(
        "Generated by `scripts/eda.py` from `data/raw/online_shoppers_intention.csv` "
        f"({n_total} sessions). Every figure below is computed at run time; re-run the "
        "script to reproduce this report."
    )
    lines.append("")
    lines.append("## 1. Target balance (`Revenue`)")
    lines.append("")
    lines.append(f"- Positive (purchase): {n_positive} ({positive_rate:.2%})")
    lines.append(f"- Negative (no purchase): {n_negative} ({1 - positive_rate:.2%})")
    lines.append(
        f"- Imbalance ratio: {n_negative / n_positive:.2f} negative sessions per positive "
        "session. This is why PR-AUC, not accuracy, is the primary evaluation metric "
        "(a trivial always-negative classifier would already reach "
        f"{1 - positive_rate:.1%} accuracy)."
    )
    lines.append("")
    lines.append("## 2. Numeric feature distributions")
    lines.append("")
    lines.append(markdown_table(numeric_summary, float_cols=("mean", "std", "min", "50%", "max")))
    lines.append("")
    lines.append("## 3. Categorical frequencies and conversion rate by category")
    lines.append("")
    for name, table in [
        ("VisitorType", visitor_rates),
        ("Weekend", weekend_rates),
        ("Month", month_rates),
        ("TrafficType", traffic_rates),
    ]:
        lines.append(f"### {name}")
        lines.append("")
        lines.append(markdown_table(table, float_cols=("conversion_rate",)))
        lines.append("")
    lines.append("## 4. Decision-relevant observations")
    lines.append("")
    lines.append(
        f"1. **Class imbalance is severe (~{positive_rate:.1%} positive).** A model or "
        "threshold policy optimized for accuracy would default toward predicting "
        "no-purchase for almost every session; PR-AUC and an explicit business-cost "
        "threshold (Section 5.4 of the blueprint) are required instead of accuracy."
    )
    lines.append(
        f"2. **Returning visitors convert at {returning_rate:.2%} vs. new visitors at "
        f"{new_rate:.2%}.** Visitor type alone is a weak but non-trivial signal; it is a "
        "legitimate, decision-time-available feature (no leakage risk)."
    )
    lines.append(
        f"3. **Engagement depth separates converters from non-converters:** sessions that "
        f"convert spend {converted_pv_mean:.0f}s average on product-related pages vs. "
        f"{not_converted_pv_mean:.0f}s for sessions that do not convert, and converters have "
        f"a lower average bounce rate ({converted_bounce_mean:.4f} vs. "
        f"{not_converted_bounce_mean:.4f} overall mean {overall_bounce_mean:.4f}). "
        "This supports including engagement-duration and bounce/exit-rate features in the "
        "deployment-safe feature set."
    )
    lines.append(
        f"4. **Conversion rate varies by month** (highest: {best_month} at "
        f"{month_rates.loc[best_month, 'conversion_rate']:.2%}; lowest: {worst_month} at "
        f"{month_rates.loc[worst_month, 'conversion_rate']:.2%}), and the dataset has no "
        "real timestamp — only a categorical month. This is a known limitation: seasonal "
        "effects exist but cannot be modeled as a true temporal holdout (see blueprint "
        "Section 4.5)."
    )
    lines.append(
        f"5. **Weekend sessions convert at {weekend_rate:.2%} vs. weekday sessions at "
        f"{weekday_rate:.2%}** — a small, plausible difference worth keeping as a feature "
        "but not worth over-interpreting given the class imbalance."
    )
    lines.append(
        "6. **`TrafficType` and `Browser`/`OperatingSystems`/`Region` are anonymized "
        "integer codes with no documented real-world mapping.** Per decision D06, this "
        "project treats `TrafficType` strictly as an anonymous channel/source proxy and "
        "does not claim to measure or causally test platform dependence from it."
    )
    lines.append("")

    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {REPORT_PATH} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
