#!/usr/bin/env python3
"""Compute baseline validation metrics and write a Markdown error report.

Uses data/processed/baseline_validation_predictions.csv (validation split
only -- the test set is never touched here) and the threshold recorded in
artifacts/metadata/baseline_metadata.json. Writes docs/baseline-report.md and
adds a validation_metrics block to the metadata JSON.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
from sklearn.metrics import (
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)

from conversion_router.data.load import load_raw_dataset

PROJECT_ROOT = Path(__file__).resolve().parent.parent
VAL_PREDICTIONS_PATH = PROJECT_ROOT / "data" / "processed" / "baseline_validation_predictions.csv"
METADATA_PATH = PROJECT_ROOT / "artifacts" / "metadata" / "baseline_metadata.json"
REPORT_PATH = PROJECT_ROOT / "docs" / "baseline-report.md"

EXAMPLE_FEATURE_COLUMNS = (
    "VisitorType",
    "Month",
    "Weekend",
    "ProductRelated",
    "ProductRelated_Duration",
    "BounceRates",
    "ExitRates",
)


def _markdown_table(df: pd.DataFrame) -> str:
    header = "| " + " | ".join(df.columns) + " |"
    sep = "|" + "|".join(["---"] * len(df.columns)) + "|"
    rows = ["| " + " | ".join(str(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([header, sep] + rows)


def main() -> None:
    if not VAL_PREDICTIONS_PATH.exists():
        raise FileNotFoundError(
            f"{VAL_PREDICTIONS_PATH} not found. Run scripts/train_baseline.py first."
        )
    predictions = pd.read_csv(VAL_PREDICTIONS_PATH)
    metadata = json.loads(METADATA_PATH.read_text(encoding="utf-8"))
    threshold = metadata["threshold_selection"]["threshold"]

    y_true = predictions["y_true"].to_numpy()
    y_proba = predictions["y_pred_proba"].to_numpy()
    y_pred = y_proba >= threshold

    pr_auc = average_precision_score(y_true, y_proba)
    roc_auc = roc_auc_score(y_true, y_proba)
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

    validation_metrics = {
        "threshold_used": threshold,
        "pr_auc": round(float(pr_auc), 4),
        "roc_auc": round(float(roc_auc), 4),
        "precision": round(float(precision), 4),
        "recall": round(float(recall), 4),
        "f1": round(float(f1), 4),
        "confusion_matrix": {
            "true_negative": int(tn),
            "false_positive": int(fp),
            "false_negative": int(fn),
            "true_positive": int(tp),
        },
        "evaluated_on": "validation_only",
    }
    metadata["validation_metrics"] = validation_metrics
    METADATA_PATH.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")

    raw_df = load_raw_dataset()
    joined = predictions.merge(
        raw_df[list(EXAMPLE_FEATURE_COLUMNS)],
        left_on="row_index",
        right_index=True,
        how="left",
    )
    joined["error_type"] = "correct"
    joined.loc[(joined.y_true == 1) & (y_pred == 0), "error_type"] = "false_negative"
    joined.loc[(joined.y_true == 0) & (y_pred == 1), "error_type"] = "false_positive"

    joined["y_pred_proba"] = joined["y_pred_proba"].round(4)

    fn_examples = (
        joined[joined.error_type == "false_negative"]
        .sort_values("y_pred_proba", ascending=False)
        .head(3)
    )
    fp_examples = (
        joined[joined.error_type == "false_positive"]
        .sort_values("y_pred_proba", ascending=False)
        .head(3)
    )

    display_cols = ["row_index", "y_true", "y_pred_proba", *EXAMPLE_FEATURE_COLUMNS]

    lines = []
    lines.append("# Baseline (Logistic Regression) Validation Report")
    lines.append("")
    lines.append(
        f"Generated by `scripts/report_baseline.py` on the validation split only "
        f"({len(predictions)} rows) using threshold={threshold} from "
        "`artifacts/metadata/baseline_metadata.json` (`threshold_selection`). "
        "The test set is not touched by this report."
    )
    lines.append("")
    lines.append("## Metrics")
    lines.append("")
    lines.append(f"- **PR-AUC (primary): {pr_auc:.4f}**")
    lines.append(f"- ROC-AUC: {roc_auc:.4f}")
    lines.append(f"- Precision: {precision:.4f}")
    lines.append(f"- Recall: {recall:.4f}")
    lines.append(f"- F1: {f1:.4f}")
    lines.append("")
    lines.append("## Confusion matrix (at selected threshold)")
    lines.append("")
    lines.append("| | Predicted negative | Predicted positive |")
    lines.append("|---|---|---|")
    lines.append(f"| Actual negative | {tn} (TN) | {fp} (FP) |")
    lines.append(f"| Actual positive | {fn} (FN) | {tp} (TP) |")
    lines.append("")
    lines.append("## Representative false negatives (missed conversions)")
    lines.append("")
    lines.append(
        "Highest predicted probability among sessions that converted but were "
        "predicted negative -- the baseline's closest misses."
    )
    lines.append("")
    lines.append(_markdown_table(fn_examples[display_cols]))
    lines.append("")
    lines.append("## Representative false positives (unnecessary reviews)")
    lines.append("")
    lines.append(
        "Highest predicted probability among sessions that did not convert but were "
        "predicted positive -- the baseline's most confident wrong calls."
    )
    lines.append("")
    lines.append(_markdown_table(fp_examples[display_cols]))
    lines.append("")

    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"PR-AUC={pr_auc:.4f} ROC-AUC={roc_auc:.4f} precision={precision:.4f} "
        f"recall={recall:.4f} f1={f1:.4f}"
    )
    print(f"Wrote {REPORT_PATH}")
    print(f"Updated {METADATA_PATH}")


if __name__ == "__main__":
    main()
